################################################################################
#
# gef-xrmi configration.
#
################################################################################
#Response Writer
geframe.xrmi.Response.BufferingSize=8192
#geframe.xrmi.Response.Encoding=UTF-8
geframe.xrmi.Response.Encoding=csWindows31J
geframe.xrmi.Response.EscapeWhiteSpace=false
