
DROP TABLE IF EXISTS `history_condition`;

CREATE TABLE `history_condition` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `HISTORY_ID` VARCHAR(36) NOT NULL,
  `HISTORY_NAME` VARCHAR(75) DEFAULT NULL,
  `SAVED_BY` VARCHAR(20) DEFAULT NULL,
  `SAVED_AT` TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_CONDITION` (`APPLICATION_ID`,`HISTORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_export_condition`;

CREATE TABLE `history_export_condition` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HISTORY_ID` VARCHAR(36) DEFAULT NULL,
  `DATASOURCE_ID` VARCHAR(75) DEFAULT NULL,
  `USE_HEADER` DECIMAL(1,0) DEFAULT NULL,
  `FILE_TYPE` VARCHAR(10) DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_EXPORT_CONDITION` (`APPLICATION_ID`,`HISTORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_export_condition_export_field`;

CREATE TABLE `history_export_condition_export_field` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HISTORY_ID` VARCHAR(36) DEFAULT NULL,
  `FIELD_ID` VARCHAR(75) DEFAULT NULL,
  `FIELD_INDEX` DECIMAL(3,0) DEFAULT NULL,
  `USE_FIELD` DECIMAL(1,0) DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_EXPORT_CONDITION_EXPORT_FIELD` (`APPLICATION_ID`,`HISTORY_ID`,`FIELD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_import_condition`;

CREATE TABLE `history_import_condition` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `HISTORY_ID` VARCHAR(36) NOT NULL,
  `DATASOURCE_ID` VARCHAR(75) DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_IMPORT_CONDITION` (`APPLICATION_ID`,`HISTORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_import_condition_filter_field`;

CREATE TABLE `history_import_condition_filter_field` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HISTORY_ID` VARCHAR(36) DEFAULT NULL,
  `FIELD_ID` VARCHAR(75) DEFAULT NULL,
  `GROUP_INDEX` DECIMAL(3,0) DEFAULT NULL,
  `FIELD_INDEX` DECIMAL(3,0) DEFAULT NULL,
  `OPERATOR` DECIMAL(2,0) DEFAULT NULL,
  `VALUE` VARCHAR(100) DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_IMPORT_CONDITION_FILTER_FIELD` (`APPLICATION_ID`,`HISTORY_ID`,`FIELD_ID`,`GROUP_INDEX`,`FIELD_INDEX`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_import_condition_import_field`;

CREATE TABLE `history_import_condition_import_field` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HISTORY_ID` VARCHAR(36) DEFAULT NULL,
  `FIELD_ID` VARCHAR(75) DEFAULT NULL,
  `FIELD_INDEX` DECIMAL(3,0) DEFAULT NULL,
  `USE_FIELD` DECIMAL(1,0) DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_IMPORT_CONDITION_IMPORT_FIELD` (`APPLICATION_ID`,`HISTORY_ID`,`FIELD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `history_import_condition_sort_field`;

CREATE TABLE `history_import_condition_sort_field` (
  `APPLICATION_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HISTORY_ID` VARCHAR(36) DEFAULT NULL,
  `FIELD_ID` VARCHAR(75) DEFAULT NULL,
  `FIELD_INDEX` DECIMAL(3,0) DEFAULT NULL,
  `SORT_ORDER` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  UNIQUE KEY `UK_HISTORY_IMPORT_CONDITION_SORT_FIELD` (`APPLICATION_ID`,`HISTORY_ID`,`FIELD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3;

