DROP TABLE "HISTORY_CONDITION" cascade constraints;
DROP TABLE "HISTORY_EXPORT_CONDITION" cascade constraints;
DROP TABLE "HISTORY_EXPORT_CONDITION_EXPORT_FIELD" cascade constraints;
DROP TABLE "HISTORY_EXPORT_FIELD" cascade constraints;
DROP TABLE "HISTORY_FILTER_FIELD" cascade constraints;
DROP TABLE "HISTORY_IMPORT_CONDITION" cascade constraints;
DROP TABLE "HISTORY_IMPORT_CONDITION_FILTER_FIELD" cascade constraints;
DROP TABLE "HISTORY_IMPORT_CONDITION_IMPORT_FIELD" cascade constraints;
DROP TABLE "HISTORY_IMPORT_CONDITION_SORT_FIELD" cascade constraints;

  CREATE TABLE "HISTORY_CONDITION" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"HISTORY_NAME" VARCHAR2(75 BYTE), 
	"SAVED_BY" VARCHAR2(20 BYTE), 
	"SAVED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_EXPORT_CONDITION" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"DATASOURCE_ID" VARCHAR2(75 BYTE), 
	"USE_HEADER" NUMBER(1,0), 
	"FILE_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_EXPORT_CONDITION_EXPORT_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"FIELD_INDEX" NUMBER(3,0), 
	"USE_FIELD" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_EXPORT_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"CONDITION_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"EXPORT_INDEX" NUMBER(3,0), 
	"EXPORT_FG" NUMBER(1,0), 
	"SORT_INDEX" NUMBER(3,0), 
	"SORT_ORDER" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_FILTER_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"CONDITION_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"FIRST_DIMENSION_INDEX" NUMBER(3,0), 
	"SECOND_DIMENSION_INDEX" NUMBER(3,0), 
	"OPERATOR" NUMBER(2,0), 
	"VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_IMPORT_CONDITION" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"DATASOURCE_ID" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_IMPORT_CONDITION_FILTER_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"GROUP_INDEX" NUMBER(3,0), 
	"FIELD_INDEX" NUMBER(3,0), 
	"OPERATOR" NUMBER(2,0), 
	"VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_IMPORT_CONDITION_IMPORT_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"FIELD_INDEX" NUMBER(3,0), 
	"USE_FIELD" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "HISTORY_IMPORT_CONDITION_SORT_FIELD" 
   (	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"HISTORY_ID" VARCHAR2(36 BYTE), 
	"FIELD_ID" VARCHAR2(75 BYTE), 
	"FIELD_INDEX" NUMBER(3,0), 
	"SORT_ORDER" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_CONDITION" ON "HISTORY_CONDITION" ("APPLICATION_ID", "HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_EXPORT_CONDITION" ON "HISTORY_EXPORT_CONDITION" ("APPLICATION_ID", "HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_EXPORT_CONDITION_EXPORT_FIELD" ON "HISTORY_EXPORT_CONDITION_EXPORT_FIELD" ("APPLICATION_ID", "HISTORY_ID", "FIELD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORYEXPORTFIELD" ON "HISTORY_EXPORT_FIELD" ("APPLICATION_ID", "CONDITION_ID", "FIELD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORYFILTERFIELD" ON "HISTORY_FILTER_FIELD" ("APPLICATION_ID", "CONDITION_ID", "FIELD_ID", "FIRST_DIMENSION_INDEX", "SECOND_DIMENSION_INDEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_IMPORT_CONDITION" ON "HISTORY_IMPORT_CONDITION" ("APPLICATION_ID", "HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_IMPORT_CONDITION_FILTER_FIELD" ON "HISTORY_IMPORT_CONDITION_FILTER_FIELD" ("APPLICATION_ID", "HISTORY_ID", "FIELD_ID", "GROUP_INDEX", "FIELD_INDEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_IMPORT_CONDITION_IMPORT_FIELD" ON "HISTORY_IMPORT_CONDITION_IMPORT_FIELD" ("APPLICATION_ID", "HISTORY_ID", "FIELD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "UK_HISTORY_IMPORT_CONDITION_SORT_FIELD" ON "HISTORY_IMPORT_CONDITION_SORT_FIELD" ("APPLICATION_ID", "HISTORY_ID", "FIELD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "HISTORY_CONDITION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISTORY_CONDITION" MODIFY ("HISTORY_ID" NOT NULL ENABLE);

  ALTER TABLE "HISTORY_IMPORT_CONDITION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISTORY_IMPORT_CONDITION" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
