################################################################################
#
# gef-ria configration.
#
################################################################################
### Repository Factory Setting.
## cache type = none|used
geframe.view.Repository.Cache=used

### Localization Settings.
geframe.view.Localizable=true

### Validator Settings.
geframe.view.Validator.Args.Separator=@@
geframe.view.Validator.MaxByteLengthCharset=UTF-8

### Authentication Check Error Page Setting.
## Deprecated. Only used in GAuthValidateFilter that is deprecated.
#geframe.view.Auth.ErrorPage=

#Ajax Settings.
geframe.richview.Response.BufferingSize=8192
geframe.richview.Response.Encoding=UTF-8
#geframe.richview.Response.Encoding=Windows-31J
#geframe.richview.Response.Encoding=csWindows31J
geframe.richview.Response.Transformer.Encoding=UTF-8
geframe.richview.SystemError.Render.Key=geframe.richview.SystemError.Render

#HTML Extension Attribute Settings.
geframe.richview.XHtml.Ex.Attr.Namespace=ghx:namespace
geframe.richview.XHtml.Ex.Attr.Widgetclass=ghx:widgetclass
geframe.richview.XHtml.Ex.Attr.Options=ghx:options
geframe.richview.XHtml.Ex.Attr.Clear=ghx:clear
geframe.richview.XHtml.Ex.Attr.Tag=ghx:tag
geframe.richview.XHtml.Ex.Attr.Format=ghx:format
geframe.richview.XHtml.Ex.Attr.Locale=ghx:locale
geframe.richview.XHtml.Ex.Attr.Initvalue=ghx:initvalue
geframe.richview.Options.Function.PlaceHolder=@@

#UI Extension Function Settings.
#geframe.richview.ui.Default.NoFocusOnReadonly=false
