################################################################################
#
# gef-ex configration.
#
################################################################################
### Framework Log Setting
geframe.core.Log.DefaultUserId=GEFRAMEWORK