# GreenEARTH Framework Configuration.#
@import.File1=gef-core-framework.properties
@import.File2=gef-auth-framework.properties
@import.File3=gef-mvc-framework.properties
@import.File4=gef-spa-framework.properties
@import.File5=gef-spa-security-framework.properties
@import.File6=gef-ria-framework.properties
@import.File7=gef-xrmi-framework.properties
@import.File8=gef-jdbc-framework.properties
@import.File9=gef-em-framework.properties
@import.File10=gef-report-framework.properties
@import.File11=gef-ex-framework.properties
@import.File12=gef-fqe-core-framework.properties