################################################################################
#
# gef-report configration.
#
################################################################################
geframe.report.Convert.Datasource.DefaultDateFormat=yyyy/MM/dd HH:mm:ss
geframe.report.Convert.Print.DefaultDateFormat=yyyy/MM/dd HH:mm
geframe.report.XmlDirectory=C:\\temp\\report\\report_xml
geframe.report.OutputDirectory=C:\\temp\\report\\report_pdf
geframe.report.ImageDirectory=C:\\temp\\report\\report_images
geframe.report.DebugMode=false
geframe.report.FontDirectory=C:\\temp\\report\\font
geframe.report.Emulate_V10=
