################################################################################
#
# gef-fqe-core configration.
#
################################################################################

geframe.fqecore.ApplicationId=jissou
geframe.fqecore.import.sort.LimitSize=5
geframe.fqecore.import.filter.group.LimitSize=3
geframe.fqecore.import.filter.group.field.LimitSize=5
geframe.fqecore.import.filter.Format.Date=dd/MM/yyyy|yyyy/MM/dd
geframe.fqecore.import.filter.Format.Number=#0.00|#
geframe.fqecore.import.LimitSize.Default=1000
geframe.fqecore.export.FileName.Default=myFile
geframe.fqecore.history.ConditionName.Default=myCondition
geframe.fqecore.datasource.CacheMode=none
geframe.fqecore.datasource.Basedir=fqe-core-datasource
geframe.fqecore.datasource.Scan.ErrorAction=ignore
geframe.fqecore.export.Escape=enable
geframe.fqecore.export.Encoding=UTF-8
