# GreenEARTH Framework Configuration.#
@import.File1=gef-core-framework.properties
@import.File2=gef-auth-framework.properties
@import.File3=gef-mvc-framework.properties
@import.File4=gef-ria-framework.properties
@import.File5=gef-xrmi-framework.properties
@import.File6=gef-jdbc-framework.properties
@import.File7=gef-em-framework.properties
@import.File8=gef-ex-framework.properties
@import.File9=gef-fqe-core-framework.properties
@import.File10=sample-application.properties