################################################################################
#
# gef-em configration..
#
################################################################################
###File Upload Setting.
geframe.em.File.TempDirectory=/tmp/geframe/upload
geframe.em.ExportFile.Encoding=Windows-31J
