################################################################################
#
# gef-public-key.json configration.
#
################################################################################
