sample.spa.keycloak.host=http://10.149.101.78:8889
sample.spa.keycloak.realmId=jissou
sample.spa.keycloak.clientId=spa
sample.spa.keycloak.clientSecret=BKt7pILs1g4ua3DoNIYpqlcAo7zb2bFb
sample.spa.keycloak.sync.account.username=user
sample.spa.keycloak.sync.account.password=user