cors:
  - id: "cors1"
    allowMethods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - HEAD
    allowOrigins:
      - http://localhost:5173
    allowHeaders:
      - Authorization
      - X-Csrf-Token
      - X-Requested-By
      - Content-Type
    allowCredentials: true
    maxAge: -1
    exposeHeaders:
      - Authorization
      - X-Csrf-Token
      - X-Requested-By
      - Content-Type
      - Csrf_token
      - Content-Disposition

rules:
  - patterns:
    - uri: "/api/*"
    authentication:
      excludes:
        - uri: "/api/users/register"
        - uri: "/api/companies*"
      processor:
        - sample.spa.JwtAuthenticationProcessor
    csrf:
      excludes:
        - uri: "/api/users/register"
        - uri: "/api/companies*"
      repository:
        cookieRepository:
          path: "/"
      tokenIssuance:
        patterns:
         - uri: "/api/csrf"
    cors:
      - config: "cors1"