name: Redmine to Slack (No Secrets)

on:
  workflow_dispatch:   # 手動実行のみ（自動スケジュールも可）

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Redmine issue
        id: get_redmine
        run: |
          REDMINE_URL="http://redmine.service.jissou.kccs.local:3000/issues/1141.json"
          REDMINE_API_KEY="c7017a6546852205f40b8a410b82ca5756842010"
          
          response=$(curl -s -H "X-Redmine-API-Key: $REDMINE_API_KEY" "$REDMINE_URL")
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Parse issue title
        id: parse
        run: |
          subject=$(echo '${{ steps.get_redmine.outputs.response }}' | jq -r '.issue.subject')
          status=$(echo '${{ steps.get_redmine.outputs.response }}' | jq -r '.issue.status.name')
          echo "subject=$subject" >> $GITHUB_OUTPUT
          echo "status=$status" >> $GITHUB_OUTPUT


      - name: Send Slack message
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${{ secrets.SLACK_CHANNEL }}\",
              \"text\": \"📌 Redmineチケット通知\n*件名*: ${{ steps.parse.outputs.subject }}\n*ステータス*: ${{ steps.parse.outputs.status }}\"
            }"
