name: Notify Redmine Issue to Slack

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日 9:00 JST（= UTC 0:00）
  workflow_dispatch:     # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Redmine issue data
        id: get_issue
        run: |
          response=$(curl -s -H "X-Redmine-API-Key: ${{ secrets.REDMINE_API_KEY }}" "${{ secrets.REDMINE_ISSUE_URL }}")
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Parse issue subject and status
        id: parse
        run: |
          subject=$(echo '${{ steps.get_issue.outputs.response }}' | jq -r '.issue.subject')
          status=$(echo '${{ steps.get_issue.outputs.response }}' | jq -r '.issue.status.name')
          echo "subject=$subject" >> $GITHUB_OUTPUT
          echo "status=$status" >> $GITHUB_OUTPUT

      - name: Send Slack message
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${{ secrets.SLACK_CHANNEL }}\",
              \"text\": \"📌 Redmineチケット通知\n*件名*: ${{ steps.parse.outputs.subject }}\n*ステータス*: ${{ steps.parse.outputs.status }}\"
            }"
